package com.supplychain.client;

import com.supplychain.model.DisruptionEvent;
import com.supplychain.model.RiskPrediction;
import com.supplychain.model.Shipment;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;
import org.springframework.web.reactive.function.client.WebClient;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

@Component
@RequiredArgsConstructor
@Slf4j
public class MLServiceClient {

    @Value("${mlservice.base-url}")
    private String mlServiceBaseUrl;

    private final WebClient.Builder webClientBuilder;



    public RiskPrediction getPrediction(Shipment shipment, List<DisruptionEvent> nearbyEvents) {
        try {
            WebClient client = webClientBuilder.baseUrl(mlServiceBaseUrl).build();

            // Build the payload for the ML service
            Map<String, Object> payload = Map.of(
                    "shipment_id", shipment.getId(),
                    "origin", shipment.getOrigin(),
                    "destination", shipment.getDestination(),
                    "transport_mode", shipment.getTransportMode().name(),
                    "carrier", shipment.getCarrier(),
                    "scheduled_departure", shipment.getScheduledDeparture().toString(),
                    "scheduled_arrival", shipment.getScheduledArrival().toString(),
                    "nearby_events", nearbyEvents.stream().map(e -> Map.of(
                            "type", e.getEventType().name(),
                            "severity", e.getSeverity().name(),
                            "location", e.getLocation(),
                            "distance_km", 100.0  // placeholder — calculate actual distance
                    )).toList()
            );

            Map<?, ?> response = client.post()
                    .uri("/predict")
                    .bodyValue(payload)
                    .retrieve()
                    .bodyToMono(Map.class)
                    .block();

            return RiskPrediction.builder()
                    .delayProbability(((Number) response.get("delay_probability")).doubleValue())
                    .estimatedDelayHours(((Number) response.get("estimated_delay_hours")).doubleValue())
                    .primaryCause((String) response.get("primary_cause"))
                    .llmExplanation((String) response.get("llm_explanation"))
                    .modelVersion((String) response.get("model_version"))
                    .build();

        } catch (Exception e) {
            log.error("ML service call failed for shipment {}: {}", shipment.getId(), e.getMessage());
            // Fallback: return a rule-based prediction
            return fallbackPrediction(shipment, nearbyEvents);
        }
    }

    // Simple rule-based fallback if ML service is down
    private RiskPrediction fallbackPrediction(Shipment shipment, List<DisruptionEvent> events) {
        double baseRisk = 0.1;
        String cause = "No significant disruptions detected";

        for (DisruptionEvent event : events) {
            switch (event.getSeverity()) {
                case CRITICAL -> { baseRisk = Math.min(baseRisk + 0.5, 0.95); cause = event.getTitle(); }
                case HIGH     -> { baseRisk = Math.min(baseRisk + 0.3, 0.85); cause = event.getTitle(); }
                case MEDIUM   -> { baseRisk = Math.min(baseRisk + 0.15, 0.6); }
                case LOW      -> { baseRisk = Math.min(baseRisk + 0.05, 0.3); }
            }
        }

        return RiskPrediction.builder()
                .delayProbability(baseRisk)
                .estimatedDelayHours(baseRisk * 48)
                .primaryCause(cause)
                .llmExplanation("Prediction generated by fallback rule engine (ML service unavailable).")
                .modelVersion("fallback-v1")
                .build();
    }
}
